services:
  en: Services
  es: Servicios 
  list:
    - header:
        en: "Consultancy"
        es: "Consultoría"
      description:
        en: "We develop models for simulation and optimization of energy systems using the Modelica Language standard. 
             We combine physics with data to ensure that our models are reliable and accurate. 
             We are committed to delivering high-fidelity models that are easily accessible and extensively documented."
        es: "Desarrollamos modelos para simulación y optimización de sistemas energéticos usando el estándar Modelica Language. 
             Combinamos física con datos para asegurar que nuestros modelos sean fiables y precisos. 
             Nos comprometemos a entregar modelos de alta fidelidad que sean fácilmente accesibles y extensamente documentados."
      icon: "bx bx-briefcase"
    - header:
        en: "Research"
        es: "Investigación"
      description:
        en: "We are involved in multiple research projects in collaboration with other international partners and universities. 
             Through innovation we deliver cutting-edge technology for our clients."
        es: "Estamos involucrados en múltiples proyectos de investigación en colaboración con otros socios internacionales y universidades. 
             A través de la innovación entregamos tecnología de vanguardia para nuestros clientes."
      icon: "bx bx-brain"
    - header:
        en: "Teaching"
        es: "Formación"
      description:
        en: "We love learning. 
             We provide tailored teaching on Modelica, software development, BOPTEST, and advanced controls like model predictive control and reinforcement learning."
        es: "Nos encanta aprender. 
            Ofrecemos formación personalizada en Modelica, desarrollo de software, BOPTEST y controles avanzados como control predictivo con modelos y reinforcement learning."
      icon: "bx bx-book"
