services:
  en: Services
  es: Servicios 
  list:
    - header:
        en: "Integration of building energy systems"
        es: "Integración de los sistemas energéticos en la edificación"
      description:
        en: "We model and simulate of your building or community, integrating all its components.
            Once modeled, we can test multiple designs and control logics, from the classic ones until the predictive and intelligent ones.
            Based on the results, we will withdraw many conclusions to optimize your building design and operation, always in an integrated way.
            Do you need to apply these services to another kind of system? Tell us!"
        es: "Modelamos y simulamos la instalación energética de tu edificio o comunidad, integrando todos sus componentes. 
            Una vez modelado, se pueden testear múltiples diseños y lógicas de control, desde las clásicas hasta las predictivas e inteligentes.
            En base a los resultados, sacaremos muchas conclusiones destinadas a optimizar el diseño y la operación de la edifición, siempre de forma integrada.
            ¿Necesitas estos servicios en otro tipo de sistema? ¡Explícanoslo!"
    - header:
        en: "Development and implementation of specialized software"
        es: "Desarrollo e implementación de software especializado"
      description:
        en: "We develop software and data science solutions tailored to integrate and optimize the operation of your energy system using predictive and intelligent algorithms.
            Do you need to implement it? We help you."
        es: "Desarrollamos soluciones de software y ciencia de datos adaptadas a optimizar la operación de tu sistema energético de forma integrada usando algoritmos predictivos e inteligentes.
            ¿Necesitas implementarlo? Te ayudamos." 
    - header:
        en: "Knowledge transfer"
        es: "Transferencia de conocimiento"
      description:
        en: "We love learning. We also realize and promote education, research, dissemination and consultancy tasks with regard to any topic related to our expertise, 
            both in-person or remotely."
        es: "Nos encanta aprender. También realizamos y promovemos actividades de educación, investigación, divulgación y consultoría en cualquier ámbito relacionado con nuestra especialidad, 
            tanto presencialmente como de forma remota."
